### ISSUE TITLE
Taskbar icons automatically disappear on desktop

### ISSUE THREAD

**Issue by BrainNotFoundException** [ChrisAnd1998/TaskbarXI#36] opened 2022-01-08 10:47 UTC
The windows icon, search and the few icons randomly disappear from the taskbar, the tray and other features are also automatically hidden on going to the desktop.
Before:
![image](https://user-images.githubusercontent.com/72143952/148641352-6e116df3-a0dd-440c-9db1-7ec7f8b500a7.png)
After:
![image](https://user-images.githubusercontent.com/72143952/148641343-2072dc79-b43a-4dc2-a8ea-1ba754bafca2.png)

**Comment by ChrisAnd1998** [comment] 2022-01-08 11:37
Is this the latest pre-release 1.0.1.0 ?

If yes:
I would like to know your build of Windows 11
Mine is: 22000.376

**Comment by BrainNotFoundException** [comment] 2022-01-09 09:27
> Is this the latest pre-release 1.0.1.0 ?
> 
> If yes: I would like to know your build of Windows 11 Mine is: 22000.376

I have the same build 22000.376
I have switched to the same pre-release now and its comparatively better but its still hiding the corner-most icon partially and the tray is hanging out
![image](https://user-images.githubusercontent.com/72143952/148676723-8c8bd9d4-ed62-4887-bac1-34ff0fe1574b.png)
I'm using the rainmeter skin in case it has something different from the main app.

**Comment by ChrisAnd1998** [comment] 2022-01-09 09:53
Not sure why that is happening. I cannot reproduce it. I would like to see your window tree.
Open the Microsoft Spy++ application. In the upper menu go to **Tree** >> **Save Tree To File**. This will export a .sxt file.
From the sxt file i am intrested in the Shell_TrayWnd part. It should look like this:

```
Window 000100CE "" Shell_TrayWnd
		Window 00020286 "DesktopWindowXamlSource" Windows.UI.Core.CoreWindow
		Window 000100D6 "Start" Start
		Window 000100D8 "" TrayDummySearchControl
		Window 000100DA "" TrayNotifyWnd
			Window 000100DC "" Button
				Window 000100DE "" Button
			Window 000100EA "System Promoted Notification Area" ToolbarWindow32
			Window 000100EE "" SysPager
				Window 000100F0 "User Promoted Notification Area" ToolbarWindow32
			Window 000100F4 "Tray Input Indicator" TrayInputIndicatorWClass
				Window 000100F6 "" IMEModeButton
				Window 000100FA "" InputIndicatorButton
			Window 00010100 "" TrayShowDesktopButtonWClass
			Window 000102A4 "DesktopWindowXamlSource" Windows.UI.Composition.DesktopWindowContentBridge
				Window 000102A6 "" Windows.UI.Input.InputSite.WindowClass
		Window 00010102 "" ReBarWindow32
			Window 000200D2 "Running applications" MSTaskSwWClass
				Window 00010104 "Running applications" MSTaskListWClass
		Window 00020294 "DesktopWindowXamlSource" Windows.UI.Composition.DesktopWindowContentBridge
			Window 00010296 "" Windows.UI.Input.InputSite.WindowClass
```




Spy++ Application: [spyxx_amd64.zip](https://github.com/ChrisAnd1998/TaskbarXI/files/7834799/spyxx_amd64.zip)

**Comment by BrainNotFoundException** [comment] 2022-01-09 12:33
Hi, the attached zip file didn't work so I installed it through visual studio ( in case you need to give this to someone else)
Here is the log you were looking for :
```
Window 00010196 "" Shell_TrayWnd
		Window 00020340 "DesktopWindowXamlSource" Windows.UI.Core.CoreWindow
		Window 0001019A "Start" Start
		Window 0001019C "" TrayDummySearchControl
		Window 0001019E "" TrayNotifyWnd
			Window 000101A0 "" Button
				Window 000101A2 "" Button
			Window 000101AE "System Promoted Notification Area" ToolbarWindow32
			Window 000101B2 "" SysPager
				Window 000101B4 "User Promoted Notification Area" ToolbarWindow32
			Window 000101B8 "Tray Input Indicator" TrayInputIndicatorWClass
				Window 000101BA "" IMEModeButton
				Window 000101BE "" InputIndicatorButton
			Window 000101C2 "" TrayShowDesktopButtonWClass
			Window 0002034C "DesktopWindowXamlSource" Windows.UI.Composition.DesktopWindowContentBridge
				Window 0001036E "" Windows.UI.Input.InputSite.WindowClass
		Window 00020146 "" ReBarWindow32
			Window 000101C4 "Running applications" MSTaskSwWClass
				Window 0004013E "Running applications" MSTaskListWClass
		Window 0002035C "DesktopWindowXamlSource" Windows.UI.Composition.DesktopWindowContentBridge
			Window 00010362 "" Windows.UI.Input.InputSite.WindowClass
```

**Comment by ChrisAnd1998** [comment] 2022-01-09 13:08
Good to know! The tree structure seems to be identical so that's not the issue.
How many monitors do you have?
What DPI percentage are they using?
What resolution?

Something must be causing this...

**Comment by BrainNotFoundException** [comment] 2022-01-09 13:56
> Good to know! The tree structure seems to be identical so that's not the issue. How many monitors do you have? What DPI percentage are they using? What resolution?
> 
> Something must be causing this...

single monitor - 1920 x 1080

**Comment by BrainNotFoundException** [comment] 2022-01-09 14:07
I used the app instead of using the rainmeter skin and I'm having this issue where it makes the taskbar transparent only when I'm on the desktop or using an application with resized window, the moment i switch to a maximized window it stops being transparent.

**Comment by BrainNotFoundException** [comment] 2022-01-09 14:15
I tried to play around with the provided functions but none of them fixed the issue

**Comment by BrainNotFoundException** [comment] 2022-01-10 12:41
Update : this issue is happening only with the rainmeter skin, I used the app and didn't face the issue.

**Comment by ChrisAnd1998** [comment] 2022-01-10 16:47
Well the rainmeter build is not updated as many as the exe file. I updated it now so if you want to use the rainmeter version you can now ;). I'll close this for now.

**Closed by ChrisAnd1998** 2022-01-10 16:47 UTC
